# Generated by Django 5.1.5 on 2025-02-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_slidertwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertwo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
